name: attitude_indicator
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.3.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/image/attitudeguidance_fixedref.svg
    - assets/image/attitudeguidance_bankguide.svg
    - assets/sound/